# Generated by Django 4.0.4 on 2022-05-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('job_title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('company_link', models.URLField(blank=True)),
            ],
        ),
    ]
