# Generated by Django 4.0.4 on 2022-05-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
