# Generated by Django 4.0.4 on 2022-05-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_alter_resume_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('start_date',)},
        ),
    ]
