# Generated by Django 4.0.4 on 2022-05-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_alter_resume_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-start_date',)},
        ),
    ]
