# Generated by Django 4.0.4 on 2022-05-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0004_alter_resume_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
    ]
