# Generated by Django 4.0.4 on 2022-06-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0005_alter_resume_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('git_url', models.URLField(blank=True, null=True)),
                ('prj_img', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
