# Generated by Django 4.0.4 on 2022-06-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0006_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='prj_img',
            new_name='project_image',
        ),
    ]
